name: crystal_uninstaller
description: "Desinstalador de Crystal Launcher"
publish_to: 'none'
version: 1.2.4-alpha

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  win32: ^5.10.1
  archive: ^4.0.7
  path_provider: ^2.1.5
  path: ^1.9.0
  window_manager: ^0.5.1
  google_fonts: ^6.2.1
  flutter_rust_bridge: ^2.7.0
  ffi: ^2.1.3
  logger: ^2.6.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/app_icon.png
